### ISSUE TITLE
alert  3 pod has unbound immediate PersistentVolumeClaims.

### ISSUE THREAD

**Issue by caoheyang** [GerritCodeReview/k8s-gerrit#10]
when I use the chart to install gerrit , It's always alter 
` 3 pod has unbound immediate PersistentVolumeClaims.`

followed is my values.file 

```
gerrit:
  replicas: 5
  canonicalWebUrl: http://c.www.heyang.com
  livenessProbe:
    initialDelaySeconds: 30
    periodSeconds: 5
    httpGet:
      path: /
      port: 8080
  readinessProbe:
    initialDelaySeconds: 5
    periodSeconds: 1
    httpGet:
      path: /
      port: 8080
  startupProbe:
    initialDelaySeconds: 10
    periodSeconds: 30
    httpGet:
      path: /
      port: 8080

storageClasses:
  default:
    name: gp2
    create: false
    provisioner: kubernetes.io/aws-ebs
    reclaimPolicy: Delete
    parameters:
      type: gp2
      fsType: ext4
  shared:
    name: efs-sc-gerrit
    create: false
    provisioner: efs.csi.aws.com
    reclaimPolicy: Delete
    parameters:
gitRepositoryStorage:
  externalPVC:
    use: false
  size: 2000Gi

ingress:
  enabled: true
  host: c.www.heyang.com
  additionalAnnotations:
    kubernetes.io/ingress.class: internet-facing
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/target-type: ip
```

ps: 
the storageClasses gp2 and  efs-sc-gerrit is earlier created.

Cloud please give me some help?

Thanks a lot.
